Class {
	#name : 'EchoQuery',
	#superclass : 'EchoTraceRecorder',
	#category : 'Echo-Model',
	#package : 'Echo',
	#tag : 'Model'
}

{ #category : 'as yet unclassified' }
EchoQuery >> diffInClass: aClass [

	"return the diff in the code for one class"
]

{ #category : 'as yet unclassified' }
EchoQuery >> diffInCode [

	"return the diff in the code"
]

{ #category : 'as yet unclassified' }
EchoQuery >> diffInMethod: aMethod [

	"return the diff in the code for one method"
]

{ #category : 'as yet unclassified' }
EchoQuery >> diffInPackage: aPackage [

	"return the diff in the code for one package"
]
